input:
  postgres_cdc:
    dsn: postgres://me:foobar@localhost:5432?sslmode=disable
    include_transaction_markers: true
    slot_name: test_slot_native_decoder
    stream_snapshot: true
    schema: public
    tables: [my_src_table]
    # Group by transaction, each message batch is all rows changed in a transaction
    # this might be massive, but might be required for foreign key constraints
    batching:
      check: '@operation == "commit"'
      # This window should be large enough that you recieve transactions in it, otherwise
      # you could see partial transactions downstream.
      period: 10s
      processors:
        # But drop the placeholder messages for start/end transaction
        - mapping: |
            root = if @operation == "begin" || @operation == "commit" {
              deleted()
            } else {
              this
            }
output:
  # Dispatch the write based on the operation metadata
  switch:
    strict_mode: true
    cases:
      - check: '@operation != "delete"'
        output:
          sql_raw:
            driver: postgres
            dsn: postgres://me:foobar@localhost:5432?sslmode=disable
            args_mapping: root = [this.id, this.foo, this.bar]
            query: |
              MERGE INTO journey_apps3_cdc AS old
              USING (SELECT
                $1 id,
                $2 foo,
                $3 bar
              ) AS new
              ON new.id = old.id
              WHEN MATCHED THEN
                UPDATE SET
                  name = case when new.updated_at > old.updated_at OR old.updated_at is null THEN new.name ELSE old.name END,
                  updated_at = greatest(new.updated_at, old.updated_at)
              WHEN NOT MATCHED THEN
                INSERT (id, name, updated_at) VALUES (
                  new.id,
                  new.name,
                  new.updated_at
                );
      - check: '@operation == "delete"'
        output:
          sql_raw:
            driver: postgres
            dsn: postgres://me:foobar@localhost:5432?sslmode=disable
            query: DELETE FROM my_dst_table WHERE id = $1
            args_mapping: root = [this.id]
